# Generated by Django 3.0.8 on 2020-07-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200730_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lname',
            new_name='last_name',
        ),
    ]
