# Generated by Django 3.1.2 on 2020-10-14 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melody', '0002_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='score',
            new_name='user_score',
        ),
    ]
